cart/urls.py
from django.urls import path, include
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name="home"),
    path('update/', views.cart_update, name='update'),
]

drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms_new/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from search import views


app_name = 'search'

urlpatterns = [
    path('', views.ProductSearchListView.as_view(), name="list"),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
# from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from django.views import generic

from drug.models import Drugs


class ProductSearchListView(LoginRequiredMixin, generic.ListView):
    template_name = 'search/view.html'
    context_object_name = 'drugs'

    def get_context_data(self, **kwargs):
        context = super(ProductSearchListView, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            return Drugs.objects.search(query)
        return Drugs.objects.none()

search/templates/search/view.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Drug List" %}{% endblock %}

{% block content %}

    {% include 'search/snippets/search-form.html' %}<br>
    {% if query %}

        <h3>Searched for {{ query }}</h3>

    {% else %}

        {% include 'search/snippets/search-form.html' %}

    {% endif %}
    <p>Drug count: {{ drug_count }}</p>
    <br>

    {% if user.is_admin %}
        <a href="{% url 'drug:register' %}">New Drug</a>
    {% endif %}

    <div>
        {% if query %}

            {% for drug in drugs %}

                <h2><a href="{% url 'drug:detail' slug=drug.slug%}">{{ drug.name }}</a></h2>
                <p>{{ drug.des|truncatewords:10 }}</p>
                <p>{{ drug.category }}</p>
                <p>{{ drug.price_snippet }}</p>

            {% empty %}

            <h2>{{ query }} not available</h2>

            {% endfor %}

        {% else %}

            <h3>{{ query }} does not exist</h3>

        {% endif %}

        <a href="{% url 'drug:list' %}">Go back to Drug list</a>

    </div>


{% endblock %}


{% block extra_body %}

{% endblock %}