cart/urls.py
from django.urls import path, include
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name="home"),
    path('update/', views.cart_update, name='update'),
]

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('signup/', SignUpView.as_view(), name='register'),
    # path('login/', login_view, name='login')
    path('<name>/profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.profile, name='profile_update'),

    # pharmacy create
    path('pharmacy_create/', views.PharmacyRegister.as_view(), name='pharmacy_create'),

    # list of pharmacy users in my pharmacy
    path('<pharmacy>/pharmacists/', views.PharmacistList.as_view(), name='pharmacist_list'),
    path('is_pharmacist/', views.pharmacist_add, name='pharmacist_add')
]

pms_new/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext_lazy as _
from allauth.account.models import EmailAddress
from django.urls import reverse

# from drug.models import Drug, Category
# from core.permissions.permissions import ROLE_LIST, role as user_role


# Create your models here.
from pms_new import settings


class City(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Pharmacy(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    # drugs = models.ForeignKey(Drug, on_delete=models.CASCADE)
    phone = PhoneNumberField(_('phone number'), blank=True, help_text=_('Number must be in international format.'))

    class Meta:
        verbose_name_plural = 'Pharmacies'

    def get_absolute_url(self):
        return reverse('drug:list')

    def __str__(self):
        return self.name


class User(AbstractUser):
    is_admin = models.BooleanField(default=False)
    is_pharmacist = models.BooleanField(default=False)

    # username = None
    email = models.EmailField(unique=True, verbose_name='Email', help_text='Enter email')
    address = models.CharField(max_length=100, help_text='Enter your area of residence', verbose_name='Address',
                               blank=True, null=True)
    phone = PhoneNumberField(_('phone number'), blank=True, help_text=_('Number must be in international format.'), null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    @property
    def email_addresses(self):
        return EmailAddress.objects.filter(user__pk=self.pk)

    @property
    def is_verified(self):
        return EmailAddress.objects.filter(verified=True).exists()


class PharmacyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    works_at = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    created_on = models.DateTimeField(_('added on'), auto_now_add=True)

    # class Meta:
    #     unique_together = (('user', 'works_at'),)

    # def __str__(self):
    #     return f'{self.user.email} | {self.works_at.name} in {self.city.name}'

    def __str__(self):
        return self.user.email


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True, related_name='profile')
    image = models.ImageField(upload_to='profile/', default='profile/default_profile.jpg')
    # created_on = models.DateTimeField(_('added on'), auto_now_add=True)

    def __str__(self):
        return self.user.email

core/forms.py
# from allauth.account.forms import SetPasswordField, PasswordField
from django import forms
from core.models import User, Profile, Pharmacy

# from phonenumber_field.modelfields import PhoneNumberField
# from django.utils.translation import ugettext_lazy as _


class SignupForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "input_text", }), required=True,)
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={"class": "input_text", }), required=True,)
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class": "input_text", }), required=False)
    address = forms.CharField(max_length=100)
    phone = forms.CharField(help_text="Number must be in international format", label="Phone Number", max_length=30, widget=forms.TextInput(attrs={"class": "input_text", }))

    class Meta:
        model = User

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.address = self.cleaned_data['address']
        user.phone = self.cleaned_data['phone']
        user.save()


class UserProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone', 'address']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class PharmacyCreateForm(forms.ModelForm):
    class Meta:
        model = Pharmacy
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from core.permissions.mixins import AdminPermissionRequiredMixin, PharmacistPermissionRequiredMixin, admin_required_permission, pharmacist_required_permission

from core import forms
from core.models import User, Pharmacy, PharmacyUser


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "core/index.html"


class UserProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/profile.html'
    model = User
    queryset = User.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super(UserProfile, self).get_context_data(**kwargs)
    #     context['name'] = self.request.user.first_name
    #     return context


# editing user profile
@login_required()
def profile(request):
    if request.method == 'POST':
        u_form = forms.UserProfile(request.POST, instance=request.user)
        p_form = forms.ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Profile was successfully updated')
            return redirect('core:profile', name=request.user.first_name)

    else:
        u_form = forms.UserProfile(instance=request.user)
        p_form = forms.ProfileForm(instance=request.user.profile)

    context = {
        'form1': u_form,
        'form2': p_form
    }

    return render(request, 'core/profile_update.html', context)


class PharmacyRegister(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.CreateView):
    template_name = 'core/pharmacy_create.html'
    model = Pharmacy
    form_class = forms.PharmacyCreateForm

    def form_valid(self, form):
        request = self.request
        form.save(commit=True)
        name = form.cleaned_data['name']
        messages.success(request, f'{name} Pharmacy was successfully created!!!')
        return super(PharmacyRegister, self).form_valid(form)


class PharmacistList(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.ListView):
    template_name = 'core/pharmacist_list.html'
    model = PharmacyUser
    paginate_by = 6
    context_object_name = 'pharmacy_users'

    def get_queryset(self):
        pharmacy = Pharmacy.objects.get(name=self.request.user.pharmacyuser.works_at)
        users = PharmacyUser.objects.filter(works_at=pharmacy)
        return users

    # def get_context_data(self, **kwargs):
    #     context = super(PharmacistList, self).get_context_data(**kwargs)
    #     pharmacy = Pharmacy.objects.get(name=self.request.user.pharmacyuser.works_at)
    #     users = PharmacyUser.objects.filter(works_at=pharmacy)
    #     context['user_email'] = users
    #     new = context.get('pharmacy_users')
    #     print(new)
    #     return context


@login_required(login_url=reversed('account_login'))
@admin_required_permission
def pharmacist_add(request):
    if request.method == 'POST':
        print(request.POST)
        user_id = request.POST.get('pharmacist_id')
        user = get_object_or_404(User, id=user_id)
        pharmacy = Pharmacy.objects.get(name=request.user.pharmacyuser.works_at)
        if user.is_pharmacist:
            user.is_pharmacist = False
            messages.success(request, f'{user.email} was successfully removed as a pharmacist to "{pharmacy}" pharmacy')
        else:
            user.is_pharmacist = True
            messages.success(request, f'{user.email} was successfully added as a pharmacist to "{pharmacy}" pharmacy')
        user.save()
        return redirect('core:pharmacist_list', pharmacy=pharmacy)
    else:
        return Http404("Forbidden request type")

    # try:
    #     product_id = request.POST.get('product_id')
    # except Products.DoesNotExist:
    #     print('product does not exist')
    #     return redirect('cart:home')
    # product_obj = Products.objects.get(id=product_id)
    # cart_obj, new_obj = Cart.objects.new_or_get(request)
    #
    # if product_obj in cart_obj.products.all():
    #     cart_obj.products.remove(product_obj)
    # else:
    #     cart_obj.products.add(product_obj)
    #
    # return redirect('cart:home')

core/templates/core/index.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Register Drug" %}{% endblock %}

{% block content %}

    <h1>Successfully login</h1>

{% endblock %}


{% block extra_body %}

{% endblock %}

core/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
</body>
</html>

core/templates/core/pharmacist_list.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "List of Pharmacy users" %}{% endblock %}

{% block content %}

    {% include 'search/snippets/search-form.html' %}<br>

    {% blocktrans with pharmacy=request.user.pharmacyuser.works_at city=request.user.pharmacyuser.city %}
        <h1>List of users in "{{ pharmacy }}" Pharmacy in "{{ city }}"</h1>
    {% endblocktrans %}


    <br>

    <div>
            <div>

                <table>
                    <thead>
                    <tr>
                        <td>Email</td>
                        <td>First Name</td>
                        <td>Last Name</td>
                        <td>Phone Number</td>
                        <td>Profile Pic</td>
                        <td>Is Pharmacist</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for pharmacy_user in pharmacy_users %}
                        <tr>
                            <td>{{ pharmacy_user.user.email }}</td>
                            <td>{{ pharmacy_user.user.first_name }}</td>
                            <td>{{ pharmacy_user.user.last_name }}</td>
                            <td>{{ pharmacy_user.user.phone }}</td>
                            <td>
                                <img src="{{ pharmacy_user.user.profile.image.url }}" alt="profile">
                            </td>
                            <td>
                                <form action="{% url 'core:pharmacist_add' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ pharmacy_user.user.id }}" name="pharmacist_id">
                                    {% if pharmacy_user.user.is_pharmacist %}
                                    <input type="submit" value="Remove">
                                    {% else %}
                                    <input type="submit" value="Add">
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>

        {% for category in category %}
            <p>{{ category.name }}</p>
        {% endfor %}
    </div>

    <br>

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}


{% endblock %}


{% block extra_body %}

{% endblock %}

core/templates/core/pharmacy_create.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Create Pharmacy" %}{% endblock %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>

{% endblock %}


{% block extra_body %}

{% endblock %}

core/templates/core/profile.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Register Drug" %}{% endblock %}

{% block content %}

    <img src="{{ request.user.profile.image.url }}" alt="image">

    <p>First Name: {{ request.user.first_name }}</p>
    <p>Last Name: {{ request.user.last_name }}</p>
    <p>Email: {{ request.user.email }}</p>
    <p>Phone Number: {{ request.user.phone }}</p>
    <p>Address: {{ request.user.address }}</p>
    <p>Woks at: {{ request.user.pharmacyuser.works_at }}</p>

    <a href="{% url 'core:profile_update' %}">Edit</a>

{% endblock %}


{% block extra_body %}

{% endblock %}

core/templates/core/profile_update.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Profile Update" %}{% endblock %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form1.as_p }}
        {{ form2.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}


{% block extra_body %}

{% endblock %}

core/templates/core/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>