cart/urls.py
from django.urls import path, include
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name="home"),
    path('update/', views.cart_update, name='update'),
]

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('signup/', SignUpView.as_view(), name='register'),
    # path('login/', login_view, name='login')
    path('<name>/profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.profile, name='profile_update'),

    # pharmacy create
    path('pharmacy_create/', views.PharmacyRegister.as_view(), name='pharmacy_create'),

    # list of pharmacy users in my pharmacy
    path('<pharmacy>/pharmacists/', views.PharmacistList.as_view(), name='pharmacist_list'),
    path('is_pharmacist/', views.pharmacist_add, name='pharmacist_add')
]

drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms_new/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drug/forms.py
from drug.models import Drugs, Category
from django import forms
from django.utils import timezone


class DrugRegistration(forms.ModelForm):
    class Meta:
        model = Drugs
        fields = ['name', 'des', 'category', 'price', 'discount_price', 'batch_no', 'image', 'expiry_date']

    # def __init__(self, request, *args, **kwargs):
    #     # question_pk = kwargs.pop('question_pk')
    #     user_pharmacy = request.user.pharmacyuser.works_at.name
    #     super(DrugRegistration, self).__init__(*args, **kwargs)
    #     if request:
    #         self.fields['pharmacy'].initial = user_pharmacy
    #         self.fields['pharmacy'].widget = forms.HiddenInput()

    def clean_expiry_date(self):
        drug_name = self.cleaned_data['name']
        expiry_date = self.cleaned_data['expiry_date']
        present_date = timezone.now().date()
        difference = int(str(expiry_date - present_date).split()[0])  # gets the number of days difference
        if difference < 1:
            raise forms.ValidationError("{} is expired".format(drug_name))
        elif difference < 7:
            raise forms.ValidationError("{} expiration date is too close".format(drug_name))
        else:
            return expiry_date

drug/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from drug.forms import DrugRegistration
from drug.models import Drugs, Category, OrderDrugs, Order, ExpiredDrugs
from core.models import Pharmacy, PharmacyUser, Profile, City
from core.permissions.mixins import AdminPermissionRequiredMixin, PharmacistPermissionRequiredMixin, admin_required_permission, pharmacist_required_permission


class DrugRegister(LoginRequiredMixin, generic.CreateView):
    template_name = 'drug/register.html'
    model = Drugs
    form_class = DrugRegistration
    # initial =

    # # overridding form field input
    # def get_initial(self):
    #     initial = super(DrugRegister, self).get_initial()
    #     print(self.initial)
    #     initial['pharmacy'] = self.kwargs.get("pk")
    #     return initial

    # def get_form_kwargs(self):
    #     kwargs = super(IdentitySocieteFormView, self).get_form_kwargs()
    #     query_Responsable = self.request.GET.get('Responsable')
    #     Responsable = Individu.objects.filter(NumeroIdentification=query_Responsable)
    #     kwargs['responsable_qs'] = Responsable
    #     u = request.user
    #     kwargs['user_initial'] = '{lname} {fname}'.format(lname=u.last_name, fname=u.first_name)
    #     return kwargs
    #
    # class SocieteFormulaire(forms.ModelForm):
    #     def __init__(self, *args, **kwargs):
    #         user_initial = kwargs.pop('user_initial', None)
    #         responsable_qs = kwargs.pop('responsable_qs', None)
    #         super(SocieteFormulaire, self).__init__(*args, **kwargs)
    #         self.fields['Responsable'].queryset = responsable_qs
    #         self.fields['InformationsInstitution'].initial = user_initial

    def form_valid(self, form):
        request = self.request
        form.instance.added_by = self.request.user
        form.instance.pharmacy = Pharmacy.objects.filter(name=request.user.pharmacyuser.works_at)[0]
        form.instance.city = City.objects.filter(name=self.request.user.pharmacyuser.city)[0]
        form.save(commit=True)
        name = form.cleaned_data['name']
        messages.success(request, f'{name} was successfully registered!!!')
        return super(DrugRegister, self).form_valid(form)


class DrugList(LoginRequiredMixin, generic.ListView):
    template_name = 'drug/list.html'
    model = Drugs
    paginate_by = 5
    context_object_name = 'drugs'
    queryset = Drugs.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pharmacy'] = Pharmacy.objects.filter(name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(pharmacy=self.request.user.pharmacyuser.works_at)
        # print(context.get('pharmacy'))
        return context


class DrugDetail(LoginRequiredMixin, generic.DetailView):
    queryset = Drugs.objects.all()
    template_name = 'drug/detail.html'
    context_object_name = 'drug'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        try:
            instance = Drugs.objects.get(slug=slug)
        except Drugs.DoesNotExist:
            raise Http404("Drug doesn't exist")
        except Drugs.MultipleObjectsReturned:
            qs = Drugs.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404('What error is this one')
        return instance

    # def get_context_data(self, **kwargs):
    #     contex = super(DrugDetail, self).get_context_data(**kwargs)
    #     contex['pharmacy'] = Drug.objects.get(pharmacy__name__startswith='m')


class DrugEdit(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.UpdateView):
    template_name = 'drug/edit.html'
    form_class = DrugRegistration
    context_object_name = 'drug'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        try:
            instance = Drugs.objects.get(slug=slug)
        except Drugs.DoesNotExist:
            raise Http404("Drug doesn't exist")
        except Drugs.MultipleObjectsReturned:
            qs = Drugs.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404('What error is this one')
        return instance

    # def form_valid(self):
    #     request = self.request
    #     messages.success(request, 'Drug was successfully Edited!!!')
    #     return super().form_valid(self)


class DrugDelete(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.DeleteView):
    model = Drugs
    template_name = 'drug/confirm_delete.html'
    context_object_name = 'drug'
    success_url = reverse_lazy('drug:list')


# adding drug to cart
@login_required(login_url=reversed('account_login'))
@pharmacist_required_permission
def add_to_cart(request, slug):
    drug = get_object_or_404(Drugs, slug=slug)
    order_drug, created = OrderDrugs.objects.get_or_create(drug=drug, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.drugs.filter(drug__slug=drug.slug).exists():
            order_drug.quantity += 1
            order_drug.save()
            messages.info(request, f'{drug.name} quantity was updated')
        else:
            order.drugs.add(order_drug)
            messages.info(request, f'{drug.name} was added to your cart')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.drugs.add(order_drug)
        messages.info(request, f'{drug.name} was added to your cart')

    return redirect('drug:order_summary')


# removing drug from cart
@login_required(login_url=reversed('account_login'))
@pharmacist_required_permission
def remove_from_cart(request, slug):
    drug = get_object_or_404(Drugs, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.drugs.filter(drug__slug=drug.slug).exists():
            order_drug = OrderDrugs.objects.filter(drug=drug, user=request.user, ordered=False)[0]
            order.drugs.remove(order_drug)
            messages.info(request, f'{drug.name} was removed from your cart')
            return redirect('drug:order_summary')
        else:
            messages.info(request, f'{drug.name} was not in your cart')
            return redirect('drug:order_summary')
    else:
        messages.info(request, "You don't have an active order")
        return redirect('drug:order_summary')


# removing single drug from cart
@login_required(login_url=reversed('account_login'))
@pharmacist_required_permission
def remove_single_drug_from_cart(request, slug):
    drug = get_object_or_404(Drugs, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.drugs.filter(drug__slug=drug.slug).exists():
            order_drug = OrderDrugs.objects.filter(drug=drug, user=request.user, ordered=False)[0]

            if order_drug.quantity > 1:
                order_drug.quantity -= 1
                order_drug.save()
            else:
                order.drugs.remove(order_drug)

            messages.info(request, f'{drug.name} quantity was updated')
            return redirect('drug:order_summary')
        else:
            messages.info(request, f'{drug.name} was not in your cart')
            return redirect('drug:detail', slug=slug)
    else:
        messages.info(request, "You don't have an active order")
        return redirect('drug:detail', slug=slug)


# order summary
class OrderSummary(LoginRequiredMixin, PharmacistPermissionRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)

            # calculating the total price of the drugs in the cart
            total = 0

            for drug in order.drugs.all():
                total += drug.get_final_price()

            context = {'drug': order, 'total': total}
            return render(self.request, 'drug/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You don not have an active order")
            return redirect('/')


# view drugs present in my pharmacy
class DrugsPharmacy(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.ListView):
    template_name = 'drug/drug_pharmacy.html'
    model = Drugs
    paginate_by = 5
    context_object_name = 'drugs'

    def get_queryset(self):
        request = self.request
        pharmacy = Pharmacy.objects.get(name=self.request.user.pharmacyuser.works_at)
        drugs = Drugs.objects.filter(added_by=request.user, pharmacy=pharmacy)
        return drugs


# get the list of expired drugs for a given pharmacy
class DrugsExpired(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.ListView):
    template_name = 'drug/expired_drugs.html'
    model = Drugs
    paginate_by = 5
    context_object_name = 'drugs'

    def get_queryset(self):
        request = self.request
        pharmacy = Pharmacy.objects.get(name=self.request.user.pharmacyuser.works_at)
        drugs = Drugs.objects.filter(added_by=request.user, pharmacy=pharmacy)

        present_date = timezone.now().date()

drug/templates/drug/confirm_delete.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Confirm Delete" %}{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ drug.name }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/detail.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Drug Details" %}{% endblock %}

{% block content %}

        <!--{{ expired_drugs }}-->

        <!--{{ date_difference }}-->
        <br>

        {% if request.user.is_admin %}

                <a href="{% url 'drug:edit' slug=drug.slug %}">Edit</a>
                <a href="{% url 'drug:delete' slug=drug.slug %}">Delete</a>

        {% endif %}

        <br>

        {% if drug.image.url is not null %}
        <img src="{{ drug.image.url }}" alt="image">
        {% endif %}

        <h2>{{ drug.name }}</h2>
        <p>{{ drug.des }}</p>
        <p>Category: {{ drug.category }}</p>
        <p>Pharmacy Found: {{ drug.pharmacy }} in {{ drug.pharmacy.city }} precisely in {{ drug.pharmacy.location }}</p>

        {% if drug.discount_price %}
            <p>Discount Price: {{ drug.discount_price }} CFA</p>
        {% else %}
            <p>Price: {{ drug.price }} CFA</p>
        {% endif %}

        <p>Batch Number: {{ drug.batch_no }}</p>
        <p>Expiry Date: {{ drug.expiry_date }}</p>

        {% if request.user.is_pharmacist %}
                <div>
                        <a href="{{ object.get_add_to_cart_url }}">Add to Cart</a><br>
                        <a href="{{ object.remove_from_cart_url }}">Remove from Cart</a>
                </div>
        {% endif %}


{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/drug_pharmacy.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Drug List" %}{% endblock %}

{% block content %}

    {% include 'search/snippets/search-form.html' %}<br>
    <h1>{% trans "List of Drugs" %}</h1>


        <p>Total Drug count: ??? </p>


    <br>

    {% if user.is_admin %}
        <a href="{% url 'drug:register' %}">New Drug</a>
        <a href="{% url 'drug:list' %}">View all drugs in the system</a>
    {% endif %}

    <h2>Here are the drugs added by {{ request.user }}</h2>

    <div>
        {% for drug in drugs %}
            <div>
                <h1><a href="{% url 'drug:detail' slug=drug.slug %}">{{ drug.name }}</a></h1>

                <p>{{ drug.des|truncatewords:10 }}</p>
                <p>{{ drug.category }}</p>

                {% if drug.discount_price %}
                    <p>{{ drug.discount_price }} CFA</p>
                {% else %}
                    <p>{{ drug.price }} CFA</p>
                {% endif %}

            </div>
        {% endfor %}

        {% for category in category %}
            <p>{{ category.name }}</p>
        {% endfor %}
    </div>

    <br>

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}


{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/edit.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Edit Drug" %}{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

    <a href="{% url 'drug:list' %}">Go back</a>

{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/expired_drugs.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Expired Drug List" %}{% endblock %}

{% block content %}

    {% include 'search/snippets/search-form.html' %}<br>
    <h1>{% trans "List of Expired Drugs" %}</h1>


    <div>
        {% for drug in drugs %}
            <div>
                <h1><a href="{% url 'drug:detail' slug=drug.slug %}">{{ drug.name }}</a></h1>

                <p>{{ drug.des|truncatewords:10 }}</p>
                <p>{{ drug.category }}</p>

                {% if drug.discount_price %}
                    <p>{{ drug.discount_price }} CFA</p>
                {% else %}
                    <p>{{ drug.price }} CFA</p>
                {% endif %}

            </div>

        {% empty %}

            <p>No drugs have expired</p>

        {% endfor %}

    </div>

    <br>

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}


{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/list.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Drug List" %}{% endblock %}

{% block content %}

    {% include 'search/snippets/search-form.html' %}<br>
    <h1>{% trans "List of Drugs" %}</h1>

    {% if request.user.is_superuser %}
        <p>Overall Drug count: {{ drug_count }}</p>
    {% endif %}

    <br>

    {% if user.is_admin %}
        <a href="{% url 'drug:register' %}">New Drug</a>
        <a href="{% url 'drug:pharmacy_drugs' pharmacy=pharmacy %}">View My drugs</a>
        <a href="{% url 'drug:expired_drugs' pharmacy=pharmacy %}">View expired drugs</a>
        <a href="{% url 'core:pharmacist_list' pharmacy=pharmacy %}">View List of Pharmacist</a>
    {% endif %}

    <div>
        {% for drug in drugs %}
            <div>
                <h1><a href="{% url 'drug:detail' slug=drug.slug %}">{{ drug.name }}</a></h1>

                <p>{{ drug.des|truncatewords:10 }}</p>
                <p>{{ drug.category }}</p>

                {% if drug.discount_price %}
                    <p>{{ drug.discount_price }} CFA</p>
                {% else %}
                    <p>{{ drug.price }} CFA</p>
                {% endif %}

            </div>
        {% endfor %}

        {% for category in category %}
            <p>{{ category.name }}</p>
        {% endfor %}
    </div>

    <br>

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}


{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/order_summary.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Drug Details" %}{% endblock %}

{% block content %}


    <p>This is my order summary</p><br>

<div>
    <table>
        <thead>
        <tr>
            <th>#</th>
            <th>Drug Name</th>
            <th>Price</th>
            <th>Discount Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>

        <tbody>
        {% for order_drug in drug.drugs.all %}

            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ order_drug.drug.name }}</td>
                <td>{{ order_drug.drug.price }}</td>
                {% if order_drug.drug.discount_price %}
                <td>{{ order_drug.drug.discount_price }}</td>
                {% else %}
                <td>-</td>
                {% endif %}
                <td>
                    <a href="{% url 'drug:remove_single_drug_from_cart' order_drug.drug.slug %}">Reduce</a>
                    {{ order_drug.quantity }}
                    <a href="{% url 'drug:add_to_cart' order_drug.drug.slug %}">Add</a></td>
                <td>
                    {% if order_drug.drug.discount_price %}
                        {{ order_drug.get_total_discount_drug_price }} CFA
                        (saving {{ order_drug.get_amount_saved }} CFA)
                    {% else %}
                        {{ order_drug.get_total_drug_price }} CFA
                    {% endif %}
                    <a href="{% url 'drug:remove_from_cart' order_drug.drug.slug %}">Remove Drug</a>
                </td>
            </tr>

        {% empty %}

            <tr>
                <td>Your cart is Empty</td>
            </tr>

            <tr>
                <td colspan="5">
                    <a href="{% url 'drug:list' %}">Continue sales</a>
                </td>
            </tr>

        {% endfor %}

        {% if total %}

            <tr>
                <td colspan="5">Total</td>
                <td>{{ total }} CFA</td>
            </tr>

            <tr>
                <td colspan="5">
                    <a href="{% url 'drug:list' %}">Continue sales</a>
                    <a href="#">Proceed to check out</a>
                </td>
            </tr>

        {% endif %}


        </tbody>
    </table>
</div>

{% endblock %}


{% block extra_body %}

{% endblock %}

drug/templates/drug/register.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Register Drug" %}{% endblock %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

{% endblock %}


{% block extra_body %}

{% endblock %}