cart/urls.py
from django.urls import path, include
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name="home"),
    path('update/', views.cart_update, name='update'),
]

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('signup/', SignUpView.as_view(), name='register'),
    # path('login/', login_view, name='login')
    path('<name>/profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.profile, name='profile_update'),

    # pharmacy create
    path('pharmacy_create/', views.PharmacyRegister.as_view(), name='pharmacy_create'),

    # list of pharmacy users in my pharmacy
    path('<pharmacy>/pharmacists/', views.PharmacistList.as_view(), name='pharmacist_list'),
    path('is_pharmacist/', views.pharmacist_add, name='pharmacist_add')
]

drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms_new/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
  <head>

    {% load cart_template_tags %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    {% block css %}{% endblock %}
  </head>
  <body>
    {% block body %}

      {% if messages %}
      <div>
        <strong>Messages:</strong>
        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                  {{ message|safe }}
              </li>
              {% endfor %}
          </ul>
        {% endif %}
      </div>
      {% endif %}

      <div>
        <strong>Menu:</strong>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'drug:list' %}">Drugs</a></li>
            {% if request.user.is_pharmacist %}
            <li><a href="{% url 'drug:order_summary' %}"><span>{{ request.user|cart_item_count }}</span> Cart</a></li>
            {% endif %}
          <li><a href="{% url 'core:pharmacy_create' %}">Create Pharmacy</a></li>
          <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
          <li><a href="{% url 'core:profile' name=request.user.first_name %}">Profile</a></li>
          <li><a href="#">Settings</a></li>
          <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
          {% else %}
          <li><a href="{% url 'account_login' %}">Sign In</a></li>
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
      {% block content %}
      {% endblock %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}

    {% block js %}{% endblock %}

  </body>
</html>